### ISSUE TITLE
PWM Bindings changed on Beaglebone Black.

### ISSUE THREAD

**Issue by kingtimm** [graycatlabs/PyBBIO#18]
Not necessarily a PyBBIO issue, but the bindings seemed to have changed quite a bit on BBB's Angstrom Distribution. I am not too familiar with the distribution, but /sys/class/pwm does not exist.

There are some clues to what has to happen in the new bonescript: https://github.com/jadonk/bonescript/blob/master/node_modules/bonescript/index.js

This discussion board post has some information too: https://groups.google.com/d/msg/beagleboard/wjbOVE6ItNg/Dym4H4HuI8gJ

**Comment by mrjaperez** [comment]
I am running in to this issue with a Beaglebone black Rev C I just purchased, by default it came with:
Linux version 3.8.13-bone47  (gcc version 4.6.3 (Debian 4.6.3-14) ) 
Debian GNU/Linux 7.4 (wheezy)

It is not the Python library, I get this same error when setting PWM manually, P8 13 does not create run, duty, period, etc interface files.

I am about to learn how to build the kernel and reflash. Any steps anyone can provide for this?
I think the file is now in ti-linux-kernel-dev/patches/defconfig
CONFIG_PWM_TIEHRPWM=m
Thanks.
