### ISSUE TITLE
AIN read performance issue

### ISSUE THREAD

**Issue by Sanerix** [graycatlabs/PyBBIO#29]
## I have wrote a small program to read as many requests as possible from AIN0:

from bbio import *
import time

bbio.bbio_init()

i = 0
j = 0
end =  time.time() + 1 
while time.time() < end:
    x = analogRead(AIN0)
    if x > 0:
        i=i+1
    else:
        j=j+1
print "have read " ,i , " times in a second with ",j," failed."
bbio.bbio_cleanup()
## I get the following output:

root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  307  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  320  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  313  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  318  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  320  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  317  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  318  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_PyBBIO.py 
have read  317  times in a second with  0  failed.
root@beaglebone:~/python# python readAIN1_console.py 
## when I do the same on Adafruit library, I get 

import Adafruit_BBIO.ADC as ADC
import time

ADC.setup()
i = 0
j = 0
end =  time.time() + 1 
while time.time() < end:
    x = ADC.read("AIN1")
    if x > 0:
        i=i+1
    else:
        j=j+1
print "have read " ,i , " times in a second with ",j," failed."

root@beaglebone:~/python# ./readAIN1_console.py 
have read  818  times in a second with  0  failed.
root@beaglebone:~/python# ./readAIN1_console.py 
have read  822  times in a second with  0  failed.
root@beaglebone:~/python# ./readAIN1_console.py 
have read  820  times in a second with  0  failed.
root@beaglebone:~/python# ./readAIN1_console.py 
have read  825  times in a second with  0  failed.
root@beaglebone:~/python# ./readAIN1_console.py 
have read  820  times in a second with  0  failed.

**Comment by Advanta09** [comment]
Where can i find 'adafruit_bbio.adc'; i was interested to know the definitions of 'adc.read', 'adc.read_raw'

**Comment by deepakkarki** [comment]
This is the wrong repository. 
You are looking for adafruit.bbio and not PyBBIO

**Comment by Advanta09** [comment]
Ok.. Problem was solved.. Thanks

-----Original Message-----
