### ISSUE TITLE
Cannot Import bbio

### ISSUE THREAD

**Issue by grizzlybair** [graycatlabs/PyBBIO#30]
Disclaimer: I'm new to Python

I'm simply trying to run the blink.py example and am getting the error:

ImportError: No module name api

I've tried searching for some answers on forums and through Google, to no avail.  I'm on a bit of a time crunch (need a working prototype in a little more than a day).  Help would be very much appreciated.

**Comment by rameshprakash** [comment]
I came across the following error
Traceback (most recent call last):
  File "speed_test.py", line 2, in <module>
    from bbio import *
ImportError: No module named bbio

I am running python in home directory.  PyBBIO directory is installed under home directory!  Please let me know how to fix this? 

Thanks,
