### ISSUE TITLE
Beaglebone with Ubuntu

### ISSUE THREAD

**Issue by bernd59** [graycatlabs/PyBBIO#4]
Hallo,

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bbio.py", line 58, in <module>
    with open("/dev/mem", "r+b") as f:
IOError: [Errno 13] Permission denied: '/dev/mem'

thanks Bernd

**Comment by akerbay** [comment]
Uh oh, it looks like this is causing me problems starting up my Python code on a BBB. Is there a way around this or is it absolutely necessary to have to run it as root?
John
