### ISSUE TITLE
Need info on PyBBIO internals - PWM analogWrite

### ISSUE THREAD

**Issue by kevin-george** [graycatlabs/PyBBIO#52]
Hi, I've found that the the analogWrite function is using the sysfs interface for generating PWM instead of /dev/mem as mentioned on the wiki. Is this is a work in progress or am i looking at the wrong file?
File i found was -> bbio/platform/beaglebone/bone_3_8/pwm.py

**Comment by alexanderhiam** [comment]
Hmm... I think I'm a little late answering... sorry about that!

By "keeping the kernel drivers happy" I'm referring to the fact that you don't want to change the state of a hardware subsystem if a currently loaded kernel driver is using it, as it will then be in a different state then the driver thinks it is and bad things will happen.
