### ISSUE TITLE
ImportError: No module named gst

### ISSUE THREAD

**Issue by BBB-USER** [graycatlabs/PyBBIO#55]
I am new to BeagleBone and I am testing out the webcam_bbioserver_test.py example provided here with PYBBIO. I get the "Importerror: no module named gst" error. I checked for gst-inspect on the OS(Angstrom) and it shows the GST module installed. Please help me understand if the webcam requires any specific gst plugin to run? or does it have something to do with the configuration.

**Comment by alexanderhiam** [comment]
That's referring to the gstreamer Python bindings, which you should hopefully be able to install on Angstrom with:
  opkg install python-gst0.10

I don't have an Angstrom image handy though, that package may not be available
