### ISSUE TITLE
bbb crash/hangs on user led 2 

### ISSUE THREAD

**Issue by BBB-USER** [graycatlabs/PyBBIO#56]
hello, i am a new user of beaglebone black and have been using PyBBIO's client server codes to access my hardware. I've modified a code relating to the PyBBIOServer_test.py to run motors instead of LEDs but making a new modified python file brings a crash with it to the beaglebone every time i edit the code or test the code so please help me out ,as i am very desperate of it since i have a  very less time relating to my project

**Comment by alexanderhiam** [comment]
What errors are you seeing? What have you modified?

**Comment by alexanderhiam** [comment]
Closing this as I haven't heard anything more, reopen it if you're still having trouble.
