### ISSUE TITLE
Update pinout diagram

### ISSUE THREAD

**Issue by alexanderhiam** [graycatlabs/PyBBIO#65]
The pinout diagram (https://github.com/graycatlabs/PyBBIO/wiki#beaglebone-pinout) needs to be updated to include all the currently supported subsystems. 

This should be done before the v0.9.4 release so it can be included in a pdf manual.

**Comment by anujdeshpande** [comment]
So SPI, I2C remain. Do you think there is a need to show that all the pins can be interrupts too ? Also, what s/w did you use to create the image ? Looks pretty neat. I don't mind finishing up this. Doesn't look like much effort.

**Comment by alexanderhiam** [comment]
eQEP as well.

It might be nice to add an index, in which case it could indicate the GPIO pins as something like 'GPIO/Interrrupt'.

I used Inkscape, but it's just an SVG. My site doesn't want to serve up SVGs right now for some reason, but you should be able to download it from here: https://gist.github.com/alexanderhiam/24ce75458b4b13c4bf9f

**Comment by alexanderhiam** [comment]
I beat you to it!

**Comment by anujdeshpande** [comment]
@alexanderhiam is faster :D 
![3961165-fun_facts_about_the_matrix_with_cool_pics_from_the_movie_19](https://cloud.githubusercontent.com/assets/969376/7224730/b476a414-e753-11e4-9475-d31a8b12abba.gif)
