### ISSUE TITLE
the need to call bbio_init()

### ISSUE THREAD

**Issue by nicktime** [graycatlabs/PyBBIO#76]
Hi,

as I understand from the sources bbio_init() gets called on import and bbio_cleanup() on app exit.
But here it says they have to be called manually:
https://github.com/graycatlabs/PyBBIO/wiki/Using-PyBBIO

**Comment by alexanderhiam** [comment]
That's correct, the init and cleanup is automatic now, that page was outdated. Fixed now, thanks!
