### ISSUE TITLE
pwmFrequency() gives no output

### ISSUE THREAD

**Issue by nicktime** [graycatlabs/PyBBIO#78]
Hi,

Just FYI.
I don't get output with current implementation.
I have a patch, I'll test it once I get hardware and make a pull request.

**Comment by alexanderhiam** [comment]
What's not working exactly? What code or you using?

pwmFrequency() doesn't enable the PWM output, it just sets the frequency being generated in the PWM module. pwmWrite() (or analogWrite()) has to be called to enable the output.

**Comment by nicktime** [comment]
I see. It seemed to me by the wiki that pwmFrequency() alone is enough, sorry. It would be nice to stress it in the wiki.

**Comment by alexanderhiam** [comment]
Just updated the wiki, should be more clear now. Thanks!
