### ISSUE TITLE
AWS IoT support

### ISSUE THREAD

**Issue by anujdeshpande** [graycatlabs/PyBBIO#89]
Would be awesome to have this https://github.com/aws/aws-iot-device-sdk-embedded-C here

**Comment by alexanderhiam** [comment]
I'm surprised they don't have an official Python SDK yet. I haven't looked at the API - would it make sense to live here? Or would it make more sense for there to be a separate Python library for it? (And is there really not yet?)

**Comment by anujdeshpande** [comment]
That would make much more sense 
:+1:

**Comment by alexanderhiam** [comment]
Yeah, I think better would be to just have a couple examples of using PyBBIO with AWS IoT once someone puts together a library for it. Anyone out there playing with AWS IoT on the BeagleBone?
